src/e/scm/RevisionControlSystem.java: Back-out the recent change to stop if we see any error messages with a zero status.  BitKeeper outputs on the error stream and then succeeds.  Here are two examples of a failed Commit which succeeded once I'd removed the test on errors.size():
Running bk delta -a -Y/tmp/e.scm.RevisionControlSystem-comment4766.tmp libs/HexOS/HexOS.cpp
libs/HexOS/HexOS.cpp revision 1.71: +25 -21 = 408
libs/HexOS/HexOS.cpp 1.71: 453 lines
java.lang.RuntimeException: Command 'bk delta -a -Y/tmp/e.scm.RevisionControlSystem-comment4766.tmp libs/HexOS/HexOS.cpp' returned status 0.

Errors were:

libs/HexOS/HexOS.cpp revision 1.71: +25 -21 = 408
libs/HexOS/HexOS.cpp 1.71: 453 lines
	at e.scm.RevisionControlSystem.throwError(RevisionControlSystem.java:234)
	at e.scm.RevisionControlSystem.execAndDump(RevisionControlSystem.java:218)
	at e.scm.BitKeeper.commit(BitKeeper.java:210)
	at e.scm.CheckInWindow$10.work(CheckInWindow.java:244)
	at e.scm.BlockingWorker.run(BlockingWorker.java:22)
Running bk delta -a -Y/tmp/e.scm.RevisionControlSystem-comment4767.tmp libs/HexOS/HexOS.cpp
delta: libs/HexOS/HexOS.cpp: no write permission
java.lang.RuntimeException: Command 'bk delta -a -Y/tmp/e.scm.RevisionControlSystem-comment4767.tmp libs/HexOS/HexOS.cpp' returned status 0.

Errors were:

delta: libs/HexOS/HexOS.cpp: no write permission
	at e.scm.RevisionControlSystem.throwError(RevisionControlSystem.java:234)
	at e.scm.RevisionControlSystem.execAndDump(RevisionControlSystem.java:218)
	at e.scm.BitKeeper.commit(BitKeeper.java:210)
	at e.scm.CheckInWindow$10.work(CheckInWindow.java:244)
	at e.scm.BlockingWorker.run(BlockingWorker.java:22)


git-svn-id: file:///home/martind/software.jessies.org/svnroot/scm@283 5bded901-cfd8-0310-8db1-92abb6e08623