src/e/scm/RevisionControlSystem.java: This is (part of) what I'd said [
The error message said that bk commit had returned 1.  [And nothing else, as I later clarified with "Only the message from checkintool saying that it failed with status 1 appeared in the box."]  The Edit errors window said:

Running bk delta -a -Y/tmp/e.scm.RevisionControlSystem-comment40516.tmp libs/console/KernelCommands.h
delta: libs/console/KernelCommands.h: no write permission
Running bk commit -Y/tmp/e.scm.RevisionControlSystem-comment40516.tmp
ERROR-Unable to lock repository for update.
java.lang.RuntimeException: Command 'bk commit -Y/tmp/e.scm.RevisionControlSystem-comment40516.tmp' returned status 1.
	at e.scm.RevisionControlSystem.throwError(RevisionControlSystem.java:231)
	at e.scm.RevisionControlSystem.execAndDump(RevisionControlSystem.java:218)
	at e.scm.BitKeeper.commit(BitKeeper.java:216)
	at e.scm.CheckInWindow$10.work(CheckInWindow.java:244)
	at e.scm.BlockingWorker.run(BlockingWorker.java:22)

].  Quite clearly, then, bk commit had returned a non-zero exit status but had output its error message to somewhere other than the ArrayList errors which were captured into the error box.  Where could they have gone?  System.out perhaps?  Put that in the errors box too.  It can't hurt to have all the information on the rare occasion when we see errors.

I've left in the change that Elliott made, even though it wouldn't have solved the reported problem.  There's reason to suppose - from the error message from delta above - that BitKeeper sometimes reports non-fatal errors and returns success.  From the subsequent behaviour (which I described to Elliott), it was clear that the delta operation had succeeded in creating a checked-in change.  Given that we don't understand checked-in but uncommitted deltas properly, we're probably best off quitting at the first sign of trouble and letting the user recover with bk citool.

That said, it's not clear to me whether that error message from delta was produced on System.out or System.err.  I've been unable to reproduce the contention between checkintool and bk ounpark on a smaller repository.  I think the checkintool Commit has to happen during the bk ounpark, but that's difficult to achieve when it happens quickly.

src/e/scm/Subversion.java: Track API.

src/e/scm/BitKeeper.java: It's inconvenient to capture the output of the bk sfiles command.  It's probably never going to return an error and, even if it does, it won't be as important as the Commit failures given that this is a read-only operation.


git-svn-id: file:///home/martind/software.jessies.org/svnroot/scm@282 5bded901-cfd8-0310-8db1-92abb6e08623