src/e/scm/Mercurial.java: "hg annotate" lines can contain whitespace in the author field (a field which can be truncated anyway). Luckily, we don't need the author field, so we were just making life hard for ourselves here. This patch fixes errors such as:
  Associated exception:
  java.lang.IllegalArgumentException: Line "alex AT alexanderweb DOT de> 2154: Alexander Schremmer <alex at alexanderweb.de>" doesn't match annotation pattern (^\s*\S+\s+(\d+): (.*)$).
  	at e.scm.AnnotatedLine.fromLine(AnnotatedLine.java:26)
  	at e.scm.Mercurial.parseAnnotatedLine(Mercurial.java:48)
  	at e.scm.RevisionView.parseAnnotations(RevisionView.java:412)
  	at e.scm.RevisionView.updateAnnotationModel(RevisionView.java:379)
  	at e.scm.RevisionView.access$1000(RevisionView.java:16)
  	at e.scm.RevisionView$6.finish(RevisionView.java:355)
  	at e.scm.BackEndWorker$1.run(BackEndWorker.java:41)
  	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
  	at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
  	at e.debug.EventDispatchThreadHangMonitor.dispatchEvent(EventDispatchThreadHangMonitor.java:191)
  	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
  	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
  	at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)


git-svn-id: file:///home/martind/software.jessies.org/svnroot/scm@473 5bded901-cfd8-0310-8db1-92abb6e08623